### ISSUE TITLE
PcapReaderIterator::consume documentation vs PcapNGReader implementation 

### ISSUE THREAD

**Issue by pluth** [rusticata/pcap-parser#9]
The documentation [here](https://github.com/rusticata/pcap-parser/blob/master/src/traits.rs#L89) says that calls to `consume` also refill the buffer, if necessary. However, the [implementation](https://github.com/rusticata/pcap-parser/blob/master/src/capture_pcapng.rs#L170) in `PcapNGReader` does not do so and only refill on explicit calls to `refill`. Neither does the legacy implementation.

I assume this is a docs issue because refilling is fallible but `consume` does not return a `Result`?

**Comment by chifflier** [comment]
Hm, I had to look twice to make sure I understand this part of the code.

I think the documentation is wrong here: `consume` does not refill the buffer, but will shit it if necessary (done by the inner `circular` buffer: https://docs.rs/circular/0.3.0/circular/struct.Buffer.html#method.consume). I dont think a refill would be wise, because it would cause multiple partial reads (and would prevent the crate user to control when reads are done).

I'll update the documentation.
